### PR TITLE
Migrate Profiles from ceramic to use dynamoDB

### PR DESCRIPTION
**Pull request by nagmak**
### What changes were made?

- Ceramic and 3ID were completely removed from the UI
- Fully replaced the GET and POST User in the UI
- we still need a UPDATE/PUT user for the modals to be updated

### Is there any background info about the change?

- Completing migration from ceramic to dynamoDB

### Are there any state changes? Mention key ones (if any)

NA

### Screenshots or Gifs✨

NA

### Any new dependencies? Why were they added?

NA

### Shortcut Link

https://app.shortcut.com/twali/story/335/migrate-profiles-from-ceramic-to-use-dynamodb

### CODE REVIEW

**Review by NickGonzalez04 — CHANGES_REQUESTED** [review]
On my end the createUser does not post to db. 

Error 504 in Network request.

**Comment by nagmak** [comment]
were u trying in vercel or your environment? let's go through it together bc it was working for me @NickGonzalez04

**Comment by nagmak** [comment]
Tried it again, was not able to reproduce the 504 error since it's working for me:

Login and profile builder
part1

Create user:

part2

Modals contain the user's info + viewing another existing user's profile:
part3

**Comment by NickGonzalez04** [comment]
> Hey @NickGonzalez04 let's go through it together since I didn't change the way you set up createUser. I tested it on the AWS environment and it was working for me yesterday

@nagmak - Realized my mistake when reviewing this as a vercel link and not a local test. I am still up for reviewing this wih you if you prefer. If not, lets ship this out!

**Review by NickGonzalez04 — APPROVED** [review]
see you soon Cermaic!

**Pull request merged**
