### PR TITLE
added fallback for missing logo and display fallback in 'work experie…

### PR DESCRIPTION
**Pull request by hone1er**
### What changes were made?
A fallback for missing company logos was added to CompanyModal and WorkExperience using the first letter of the company name

### Is there any background info about the change?
- Added a state to track the logo status- Also prevents the logo from disappearing when a field that is not 'companyName' is edited
### Are there any state changes? Mention key ones (if any)
Logo state is now being tracked
- Default: false
- Updated: 
```
{
message: domain: "twitter.com"
    logo: "https://logo.clearbit.com/twitter.com"
    name: "Twitter"
    options: {}
}
```

### Screenshots or Gifs✨
Fallback in profile update

Screen Shot 2022-02-22 at 2 56 37 PM

Fallback in work experience section
Screen Shot 2022-02-22 at 2 56 21 PM

### Any new dependencies? Why were they added?
not today

### Shortcut Link

https://app.shortcut.com/twali/story/270/build-a-fallback-for-company-logos-if-the-image-does-not-exist

### CODE REVIEW

**Comment by hone1er** [comment]
Looks like a check is failing but i'm not really sure why 🤔

**Comment by nagmak** [comment]
@hone1er just checked the build, and it's showing me this error, hopefully that helps narrow it down!

Screen Shot 2022-02-22 at 12 12 41 PM

**Review by nagmak — APPROVED** [review]
LFG! 🔥

**Comment by NickGonzalez04** [comment]
@hone1er I know you said there was a save issue on reload. Is this good or still fixing?

**Comment by hone1er** [comment]
> @hone1er I know you said there was a save issue on reload. Is this good or still fixing?

Still working on it, should be done tomorrow I hope. If i can't get it tomorrow I'll close the pull request until I can

**Comment by hone1er** [comment]
Re-opening this with my janky temp fix of page reload between bio/work experience update and `readProfile()` data fetch

**Comment by nagmak** [comment]
Looks good to me! I noticed that now the page reloads when someone clicks save which works for me well.

**Pull request closed without merging**
