### PR TITLE
Staging deploy test

### PR DESCRIPTION
**Pull request by NickGonzalez04**
### What changes were made?

- Removed old deploy `.severless-nextjs` files and deployed a new instance to generate new files.

### Is there any background info about the change?

- IAM policies were updated and were not accessing previously deployed resources correctly.

### Are there any state changes? Mention key ones (if any)

N/A

### Screenshots or Gifs✨

Screen Shot 2022-03-24 at 9 48 24 AM

### Any new dependencies? Why were they added?

N/A

### Shortcut Link

https://app.shortcut.com/twali/story/614/fix-deployment-issues-with-new-iam-policies

### CODE REVIEW

**Review by nagmak — CHANGES_REQUESTED** [review]
Aren't most of these hidden generated files from .serverless? We should remove them on our branches since a new deployment occurs anyway. The serverless.yml looks good though!

**Review by hone1er — APPROVED** [review]
🛠

**Comment by NickGonzalez04** [comment]
> Aren't most of these hidden generated files from .serverless? We should remove them on our branches since a new deployment occurs anyway. The serverless.yml looks good though!

Yea, you are right. If you keep the .serverless it will keep that same instance such as bucket, lambda's, and cloudfront. If I understand correctly. Definitely remove the files locally 👍 .

**Comment by nagmak** [comment]
Is there a way to set the bucket in the serverless.yml? Ideally we shouldn't have any generated files in our branches... but if that's not possible then its fair to keep it here!

**Review by nagmak — APPROVED** [review]
LFGGGGGG 🚀

**Pull request merged**
